apiVersion: artifact.apicurio.io/v1alpha1
kind: Apicurio
metadata:
  name: artifact-openapi-external-sample
spec:
  artifactId: artifact-openapi-external-sample
  name: pets-api-external
  description: "super pets api, definition from url"
  type: OPENAPI
  username: dweber019
  labels:
    - openapi
    - api
  properties:
    custom1: bubu
    custom2: lala
  state: ENABLED
  ruleValidity: FULL
  ruleCompatibility: NONE
  contentType: "application/json"
  externalContent: https://raw.githubusercontent.com/dweber019/apicurio-registry-artifact-operator/master/config/samples/openapi_example.json
